name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: sudo apt-get install build-essential doxygen
      - name: Compile
        run: |
          CFLAGS="-O3" make -j$(nproc) compile
      - name: Docs
        run: make docs
      - name: Package Release Artifact
        run: |
          DESTDIR="release" make install
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fpkg.tar.gz
          path: release

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make compile test
      run: make compile test
